### PR TITLE
merge of tmLQCD master

### PR DESCRIPTION
**Pull request by sbacchio**

### CODE REVIEW

**Comment by kostrzewa** [comment]
I think you might have found a github bug... :)

**Comment by kostrzewa** [comment]
Actually, no. The conflict is some white-space in `read_input.l` just under `use_qudainverter`

**Comment by kostrzewa** [comment]
if you search for `HEAD` in `read_input.l`, you will find the conflicting lines.

**Comment by kostrzewa** [comment]
line 195 :)

**Comment by sbacchio** [comment]
yes indeed, fine thanks!

**Pull request merged**
