### PR TITLE
Solve mmd nd shiftbyshift

### PR DESCRIPTION
**Pull request by sbacchio**

### CODE REVIEW

**Comment by kostrzewa** [comment]
@sbacchio @urbach @Finkenrath We could also first merge the shift-by-shift solver into etmc/master first.

**Comment by kostrzewa** [comment]
I also don't understand why this branch and etmc/master seem to have diverged despite having been merged together quite recently. There should be just two commits coming from `solve_mmd_nd_shiftbyshift`

**Comment by kostrzewa** [comment]
Before proceeding here, could we please merge the DDalphaAMG interface into etmc/maste? Otherwise, the resulting pull-request, once the 1+1 bit is included, will be massive and even more difficult to review. Any changes and/or bug fixes can always be pulled in later.

**Comment by urbach** [comment]
can I strongly support Barteks point here!?

**Comment by sbacchio** [comment]
@kostrzewa @urbach 
ok I will do some small changes to the interface and then merge to etmc/master and then complete this pull request

**Comment by sbacchio** [comment]
Included in pull request #7 .
Closing

**Pull request closed without merging**
